DEVICE_PATH := device/xtc/msm8937_32go_i25

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := generic
TARGET_USES_MKE2FS := true

TARGET_KERNEL_SOURCE := kernel/xtc/msm8937_32go_i25
TARGET_KERNEL_CONFIG := msm8937_32go_i25_defconfig
TARGET_KERNEL_ARCH := arm
KERNEL_CLANG_VERSION := r416183b
KERNEL_TOOLCHAIN := $(ANDROID_BUILD_TOP)/prebuilts/clang/host/linux-x86/clang-$(KERNEL_CLANG_VERSION)/bin

BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_FLASH_BLOCK_SIZE := 131072
PRODUCT_SHIPPING_API_LEVEL := 27

TARGET_BOARD_PLATFORM := msm8937
TARGET_BOOTLOADER_BOARD_NAME := QC_Reference_Phone
TARGET_NO_BOOTLOADER := true


TARGET_SCREEN_DENSITY := 320


VENDOR_SECURITY_PATCH := 2021-08-01
BOARD_AVB_ENABLE := false  


TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/etc/fstab.qcom
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true


TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop


PRODUCT_SOONG_NAMESPACES += $(DEVICE_PATH)


PRODUCT_PACKAGES += QtiTelephonyService



BOARD_SEPOLICY_VERS := 27

include vendor/xtc/msm8937_32go_i25/BoardConfigVendor.mk
